//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorManage.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTMENT()
        {
            this.DOCTORMODEL = new HashSet<DOCTORMODEL>();
        }
    
        public int DEPARTMENTID { get; set; }
        public string DEPARTMENTNAME { get; set; }
        public string CREATEBY { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public System.DateTime UPDATEDATE { get; set; }
        public bool DELETEFLAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTORMODEL> DOCTORMODEL { get; set; }
    }
}
